

query chartSecurityPrice(
  $range: HistoricalRange!
  $securityId: String!
  $options: ChartPriceRangeOptions
) {
  chartSecurityPrice(
    range: $range
    securityId: $securityId
    options: $options
  ) {
    change
    changeOverTime
    changePercent
    close
    date
    fClose
    fHigh
    fLow
    fOpen
    fVolume
    high
    id
    key
    label
    low
    marketChangeOverTime
    open
    subkey
    symbol
    uClose
    uHigh
    uLow
    uOpen
    uVolume
    updated
    volume
  }
}


query plaidLinkToken {
  plaidLinkToken
}


fragment AllHoldingData on Holding {
  _id
  # Market data fields
  marketValue
  exposure
  profitLossUsd
  profitLossPercent
  dailyProfitLossUsd
  #

  averagePrice
  costBasis
  brokerFees
  institutionValue
  direction
  quantity
  assetClass
  source
  currency
  importedSecurity {
    ...AllImportedSecurityData
  }
  security {
    ...AllSecurityData
  }
}


fragment FullPlaidAccount on PlaidAccount {
  type
  name
  subtype
  official_name
  account_id
  balances {
    current
    available
  }
}


fragment PortfolioSummary on Portfolio {
  _id
  cash
  owner {
    ...FullUser
  }
  name
  description
  private
  createdAt
  updatedAt
  plaidAccount {
    ...FullPlaidAccount
  }
  totalValue
}

fragment PortfolioTransactions on Portfolio {
  transactions {
    ...AllTransactionData
  }
}
fragment PortfolioHoldings on Portfolio {
  holdings {
    ...AllHoldingData
  }
}

fragment AllPortfolioData on Portfolio {
  ...PortfolioSummary
  ...PortfolioHoldings
  ...PortfolioTransactions
}


fragment AllTransactionData on Transaction {
  _id
  name
  date
  currency
  security {
    ...AllSecurityData
  }
  importedSecurity {
    ...AllImportedSecurityData
  }
  quantity
  amount
  fees
  price
  type
  subType
}


mutation portfoliosAddHolding($_id: ObjectId!, $input: AddHoldingInput!) {
  portfoliosAddHolding(_id: $_id, input: $input) {
    _id
    holdings {
      averagePrice
      brokerFees
      costBasis
      quantity
    }
  }
}


mutation portfoliosBeginImport($publicToken: String!) {
  portfoliosBeginImport(publicToken: $publicToken) {
    importedIds
  }
}


query portfoliosCreated {
  portfoliosCreated {
    _id
    owner {
      ...FullUser
    }
    name
    cash
    private
    description
    updatedAt
    createdAt
    totalValue
    plaidAccount {
      ...FullPlaidAccount
    }
    top5Holdings {
      costBasis
      exposure
      assetClass
      marketValue
      importedSecurity {
        ...AllImportedSecurityData
      }
      security {
        ...SecuritySummary
      }
    }
  }
}



query portfoliosFindById($_id: ObjectId!) {
  portfoliosFindById(_id: $_id) {
    _id
    ...AllPortfolioData
  }
}

mutation portfoliosInitEmpty {
  portfoliosInitEmpty {
    _id
  }
}


mutation portfoliosRemoveHolding(
  $portfolioId: ObjectId!
  $holdingId: ObjectId!
) {
  portfoliosRemoveHolding(portfolioId: $portfolioId, holdingId: $holdingId)
}


mutation portfoliosRemoveMultiple($_ids: [ObjectId!]!) {
  portfoliosRemoveMultiple(_ids: $_ids) {
    acknowledged
    deletedCount
  }
}


mutation portfoliosRemoveOne($_id: ObjectId!) {
  portfoliosRemoveOne(_id: $_id) {
    _id
  }
}


mutation portfoliosUpdateOne($_id: ObjectId!, $input: UpdatePortfolioInput!) {
  portfoliosUpdateOne(_id: $_id, input: $input) {
    _id
    createdAt
    description
    name
    private
    updatedAt
  }
}


fragment AllSecurityData on Security {
  _id
  currency
  exchange
  assetClass
  figi
  name
  region
  tickerDetails {
    ...AllTickerDetails
  }

  tickerSnapshot {
    ...AllTickerSnapshot
  }
}

fragment AllImportedSecurityData on ImportedSecurity {
  close_price
  name
  ticker_symbol
  currency
  assetClass
}

fragment SecuritySummary on Security {
  _id
  name
  region
}


fragment AllTickerDetails on TickerDetails {
  active
  cik
  currencyName
  description
  homepageUrl
  iconUrl
  listDate
  logoUrl
  market
  marketCap
  name
  phoneNumber
  shareClassOutstanding
  sicCode
  sicDescription
  totalEmployees
  type
  weightedSharesOutstanding
}


fragment AllTickerSnapshot on TickerSnapshot {
  day {
    c
    h
    l
    o
    v
    vw
  }
  lastQuote {
    P
    S
    p
    s
    t
  }
  lastTrade {
    c
    i
    p
    s
    t
    x
  }
  min {
    av
    c
    h
    l
    o
    v
    vw
  }
  prevDay {
    c
    h
    l
    o
    v
    vw
  }
  ticker
  todaysChange
  todaysChangePerc
  updated
}


query securitiesFindById($_id: String!) {
  securitiesFindById(_id: $_id) {
    _id
    ...AllSecurityData
  }
}


query securitiesSearch($searchTerm: String!) {
  securitiesSearch(searchTerm: $searchTerm) {
    _id
    ...AllSecurityData
  }
}


fragment FullUser on User {
  _id
  displayName
  emails
  photos
  createdAt
  updatedAt
}


query usersFindById($_id: ID!) {
  usersFindById(_id: $_id) {
    _id
    ...FullUser
  }
}


mutation usersFindOrCreate($input: CreateUserInput!) {
  usersFindOrCreate(input: $input) {
    _id
    ...FullUser
  }
}
