query chartPriceRange(
  $range: HistoricalRange!
  $symbolId: ObjectId!
  $options: ChartPriceRangeOptions
) {
  chartPriceRange(range: $range, symbolId: $symbolId, options: $options) {
    id
    key
    subkey
    date
    updated
    change
    changePercent
    open
    close
    high
    volume
    label
  }
}
