apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baggers-ingress
  labels:
    name: baggers-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: ui
                port:
                  number: 80
