fragment AllHoldingData on Holding {
  # Market data fields
  marketValue
  exposure
  profitLossUsd
  profitLossPercent
  dailyProfitLossUsd
  #

  averagePrice
  costBasis
  brokerFees
  direction
  quantity
  type
  source
  currency
  security {
    _id
    name
    symbol
    symbolType
    exchange
    currency
    exchangeName
    region
    quote {
      ...AllQuoteData
    }
  }
}

fragment PortfolioSummary on Portfolio {
  _id
  cash
  owner {
    ...FullUser
  }
  name
  description
  private
  createdAt
  updatedAt
  totalValue
  #   performance {
  #     ytdReturnPercent
  #     ytdReturnDollars
  #     dailyReturnPercent
  #     dailyReturnDollars
  #   }

  #   plaid {
  #     isLinked
  #   }
}

fragment PortfolioTransactions on Portfolio {
  transactions {
    ...AllTransactionData
  }
}
fragment PortfolioHoldings on Portfolio {
  holdings {
    ...AllHoldingData
  }
}

fragment AllPortfolioData on Portfolio {
  ...PortfolioSummary
  ...PortfolioHoldings
  ...PortfolioTransactions
  #   plaid {
  #     isLinked
  #     missingSecuritiesError {
  #       message
  #       missingSymbols {
  #         symbol
  #         name
  #         exchange
  #         figi
  #       }
  #     }
  #   }
}

fragment AllTransactionData on Transaction {
  name
  date
  currency
  quantity
  price
  type
  subType
}

mutation portfoliosAddHolding($_id: ObjectId!, $input: AddHoldingInput!) {
  portfoliosAddHolding(_id: $_id, input: $input) {
    _id
    holdings {
      averagePrice
      brokerFees
      costBasis
      quantity
    }
  }
}

mutation portfoliosBeginImport($publicToken: String!) {
  portfoliosBeginImport(publicToken: $publicToken) {
    _id
    createdAt
    portfolios {
      name
      cash
      transactions {
        name
        price
        quantity
        subType
        type
        date
        currency
        baggersSecurity {
          symbol
          _id
        }
        importedSecurity {
          security_symbol
          name
        }
      }
    }
  }
}

query portfoliosCreated {
  portfoliosCreated {
    _id
    owner {
      displayName
      photos
    }
    updatedAt
    createdAt
    totalValue
    top5Holdings {
      costBasis
      exposure
      marketValue
      security {
        symbol
      }
    }
  }
}

query portfoliosFindById($_id: ObjectId!) {
  portfoliosFindById(_id: $_id) {
    _id
    ...AllPortfolioData
  }
}

mutation portfoliosInitEmpty {
  portfoliosInitEmpty {
    _id
  }
}

mutation portfoliosRemoveMultiple($_ids: [ObjectId!]!) {
  portfoliosRemoveMultiple(_ids: $_ids) {
    acknowledged
    deletedCount
  }
}

mutation portfoliosRemoveOne($_id: ObjectId!) {
  portfoliosRemoveOne(_id: $_id) {
    _id
  }
}

mutation portfoliosUpdateOne($_id: ObjectId!, $input: UpdatePortfolioInput!) {
  portfoliosUpdateOne(_id: $_id, input: $input) {
    _id
    cash
    createdAt
    description
    name
    private
    updatedAt
  }
}

fragment AllQuoteData on Quote {
  avgTotalVolume
  calculationPrice
  change
  changePercent
  companyName
  close
  closeSource
  closeTime
  currency
  delayedPrice
  delayedPriceTime
  extendedPrice
  extendedChange
  extendedChangePercent
  extendedPriceTime
  high
  highSource
  highTime
  iexAskPrice
  iexAskSize
  iexBidPrice
  iexBidSize
  iexClose
  iexCloseTime
  iexLastUpdated
  iexOpen
  iexOpenTime
  iexRealtimePrice
  iexRealtimeSize
  iexMarketPercent
  iexVolume
  isUSMarketOpen
  lastTradeTime
  latestPrice
  latestSource
  latestTime
  latestUpdate
  latestVolume
  low
  lowTime
  lowSource
  marketCap
  oddLotDelayedPrice
  oddLotDelayedPriceTime
  open
  openSource
  openTime
  peRatio
  previousClose
  previousVolume
  primaryExchange
  symbol
  week52High
  week52Low
  volume
  ytdChange
}

fragment AllTickerData on Security {
  cik
  createdAt
  currency
  exchange
  exchangeName
  figi
  iexId
  name
  region
  symbol
  symbolType
  updatedAt
}

query securitiesFindById($_id: ObjectId!) {
  securitiesFindById(_id: $_id) {
    _id
    ...AllTickerData
    quote {
      ...AllQuoteData
    }
  }
}

query securitiesSearch($searchTerm: String!) {
  securitiesSearch(searchTerm: $searchTerm) {
    _id
    ...AllTickerData
    quote {
      ...AllQuoteData
    }
  }
}

fragment FullUser on User {
  _id
  displayName
  emails
  photos
  createdAt
  updatedAt
}

query usersFindById($_id: ID!) {
  usersFindById(_id: $_id) {
    _id
    ...FullUser
  }
}

mutation usersFindOrCreate($input: CreateUserInput!) {
  usersFindOrCreate(input: $input) {
    _id
    ...FullUser
  }
}
