query portfoliosCreated {
  portfoliosCreated {
    _id
    owner {
      displayName
      photos
    }
    name
    cash
    private
    description
    updatedAt
    createdAt
    totalValue
    plaidAccountType
    plaidAccountId
    top5Holdings {
      costBasis
      exposure
      marketValue
      importedSecurity {
        ...AllImportedSecurityData
      }
      security {
        ...SecuritySummary
      }
    }
  }
}
