query portfoliosCreated {
  portfoliosCreated {
    _id
    owner {
      displayName
      photos
    }
    name
    cash
    private
    description
    updatedAt
    createdAt
    totalValue
    plaidAccount {
      type
      subtype
      name
    }
    top5Holdings {
      costBasis
      exposure
      securityType
      marketValue
      importedSecurity {
        ...AllImportedSecurityData
      }
      security {
        ...SecuritySummary
      }
    }
  }
}
