query portfoliosCreated {
  portfoliosCreated {
    _id
    owner {
      displayName
      photos
    }
    updatedAt
    createdAt
    totalValue
    top5Holdings {
      costBasis
      exposure
      marketValue
      ticker {
        symbol
      }
    }
  }
}
