fragment AllSecurityData on Security {
  _id
  currency
  exchange
  assetClass
  figi
  name
  region
  tickerDetails {
    ...AllTickerDetails
  }

  tickerSnapshot {
    ...AllTickerSnapshot
  }
}

fragment AllImportedSecurityData on ImportedSecurity {
  close_price
  name
  ticker_symbol
  currency
  assetClass
}

fragment SecuritySummary on Security {
  _id
  name
  region
}
