fragment AllTickerSnapshot on TickerSnapshot {
  day {
    c
    h
    l
    o
    v
    vw
  }
  lastQuote {
    P
    S
    p
    s
    t
  }
  lastTrade {
    c
    i
    p
    s
    t
    x
  }
  min {
    av
    c
    h
    l
    o
    v
    vw
  }
  prevDay {
    c
    h
    l
    o
    v
    vw
  }
  ticker
  todaysChange
  todaysChangePerc
  updated
}
