schema: 
  -  http://localhost:5000/graphql:
        headers:
          Authorization: ${API_TOKEN}

documents: "**/*.document.gql"
plugins:
  - typescript
  - typescript-operations
  - typescript-resolvers
  - typescript-react-apollo
