fragment AllHoldingData on Holding {
  # Market data fields
  marketValue
  exposure
  profitLossUsd
  profitLossPercent
  dailyProfitLossUsd
  #

  averagePrice
  costBasis
  brokerFees
  direction
  quantity
  type
  source
  currency
  security {
    _id
    name
    symbol
    symbolType
    exchange
    currency
    exchangeName
    region
    quote {
      ...AllQuoteData
    }
  }
}
