fragment AllTransactionData on Transaction {
  _id
  name
  date
  currency
  security {
    name
    symbol
  }
  importedSecurity {
    name
    ticker_symbol
  }
  quantity
  amount
  fees
  price
  type
  subType
}
