fragment AllHoldingData on Holding {
  _id
  # Market data fields
  marketValue
  exposure
  profitLossUsd
  profitLossPercent
  dailyProfitLossUsd
  #

  averagePrice
  costBasis
  brokerFees
  institutionValue
  direction
  quantity
  assetClass
  source
  currency
  importedSecurity {
    ...AllImportedSecurityData
  }
  security {
    ...AllSecurityData
  }
}
