name: Unit Tests

on:
  pull_request:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Install
         run: npm ci
       - name: "Typecheck"
         run: npm run typecheck 
       - name: "Lint"
         run: npm run lint